agent:
  cdss:
    ###一次只对一个query 和 history 打标签###
    one_qa_labeling_prompt: >
      """
        # 角色
        你是一个医生，你需要根据用户query分析意图。意图包含BMI计算，预产期和孕周计算，药品咨询,其他，共4种类别。
        # 用户query分意图析
        ## BMI计算
        如果用户query中包含身高体重，则属于计算BMI意图；如果用户query没有身高体重，但上文对话中有则不算BMI计算意图
        ## 预产期孕期计算：
        如果用户query包含末次月经日期，且用户在孕期，则属于预产期孕期计算；如果用户query中不包含日期，但上文中对话中包含，则不算预产期孕期计算意图
        ## 药品答疑
        用户query是疑问句，且是咨询药品的用法用量，成分，药物禁忌，注意事项的问题，则属于药品答疑意图；如果用户询问购买相关问题不算此类意图。
        ## 其他、
        不属于以上三类意图，则属于其他意图
        # 输出内容要求：
        {{"label":意图类别标签， 只能从["BMI","孕期孕周","药品", "其他"]选取一个作为标签, "reason":"判定具体的原因"}}，不要用markdown格式输出
        # 示例
          示例1：
                医患对话历史：
                    医生:程度不重，考虑有胰岛素抵抗，有什么其他疾病吗？您目前的身高体重是多少呢?
                    患者：有多囊卵巢
                    患者：163cm 190斤 
                输出结果:{{"label":"BMI", "reason":"患者提到了身高体重内容且给出了具体值，所以属于BMI计算的意图"}}
            示例2:
                医患对话历史：
                    患者：您好！上周六做的B超有一点积液。今晚发现有一些褐色的血
                    医生：现在怀孕多少周？
                    医生：请问平时月经多长时间来一次？一次来几天？最后一次是什么时候来的？
                    患者：2024年4月5号来的
                输出结果:{{"label":"孕期孕周", "reason":"医生咨询了孕周内容， 患者也提供了末次月经的时间，所以属于孕期孕周的意图"}}
            示例3:
                医患对话历史：
                    用户: 氢溴酸氘瑞米德韦片 0.1g*36片/瓶/盒
                    医生: 目前是确诊新型冠状病毒感染吗
                    用户: 是
                    医生: 好的
                    医生: 涉及到用药，您之前是否过药物和食物敏史，以及慢性疾病，有无肝肾功异常？7天内饮酒，如有在口服药物请告知我（没有上述情况可以回复：无）
                    用户: 无
                    医生: 目前有什么不适症状，比如：咽干、咽痛、干咳、头痛、发热等？"
                    用户：有一些
                输出结果:{{"label":"其他", "reason":"用户说有一些，不是问句，也没有咨询药品问题"}}
            示例4:
                医患对话历史：
                    患者:您好，退烧吃哪个布洛芬
                    医生:您好，我是京东健康全职范彬医生，非常高兴由我为您提供医疗咨询服务，请稍等，我正在详细阅读您的病情描述。
                    医生:布洛芬缓释胶囊或布洛芬片均可。成人每次200毫克，每6-8小时一次。
                    患者:发烧，咳嗽
                    医生:之前是否过药物和食物敏史，以及慢性疾病，有无肝肾功异常？7天内饮酒，如有在口服药物请告知我（没有上述情况可以回复：无）
                    患者:止疼的吃哪个？
                    患者：感冒吃感康可以么？
                输出结果:{{"label":"药品", "reason":"患者问感冒是否可以吃感康药， 属于用药意图"}}
        # 对话历史内容：
          {history}
        # 用户当下问题：
          {input}
      """
    ###一次性对所有的query打标签###
    all_qa_labeling_prompt: >
      """
        # 角色
        你是一个医生，你需要根据用户每轮的query分析和意图类别。意图包含BMI计算，预产期和孕周计算，药品咨询,其他，共4种类别。
        # 用户query分意图析
        ## BMI计算
        如果用户query中包含身高体重，则属于计算BMI意图；如果用户query没有身高体重，但上文对话中有则不算BMI计算意图
        ## 预产期孕期计算：
        如果用户query包含末次月经日期，且用户在孕期，则属于预产期孕期计算；如果用户query中不包含日期，但上文中对话中包含，则不算预产期孕期计算意图
        ## 药品答疑
        用户query是疑问句，且是咨询药品的用法用量，成分，药物禁忌，注意事项的问题，则属于药品答疑意图；如果用户询问购买相关问题不算此类意图。
        ## 其他、
        不属于以上三类意图，则属于其他意图
        # 输出内容要求：
        [{{"index":整数，含义为当前query在对话中的行数，包括医生回答也计算在内,"label":意图类别标签， 只能从["BMI","孕期孕周","药品", "其他"]选取一个作为标签, "reason":"判定具体的原因","content":具体判断的用户query内容}}]，不要用markdown格式输出
        # 示例
        示例1：
            医患对话历史：
                患者：有多囊卵巢
                医生:程度不重，考虑有胰岛素抵抗，有什么其他疾病吗？您目前的身高体重是多少呢?
                患者：163cm 190斤 
            输出结果:[{{"index":0,"label":"其他", "reason":"属于其他类型", "content":"患者：有多囊卵巢"}},{{"index":2,"label":"BMI", "reason":"患者提到了身高体重内容且给出了具体值，所以属于BMI计算的意图", "content":"患者：163cm 190斤"}}]
        现给出医患对话如下， 请给出用户每一轮的问题的意图结果。
        1、注意目标是判断用户的意图，在对话中内容以“用户或者患者开头”；
        2、index 为用户问题在对话历史的索引，具体为对话历史用“\n”进行分隔得到的list中的下表索引， 注意索引的正确性， 不要越界，范围：0-len(list)-1
        {0}
      """
    ## 孕期孕周 单个类别的识别 prompt##
    one_qa_for_pregnancy_labeling_prompt: >
      """
        你将根据以下定义来判断用户的query是否属于预产期、孕期计算意图。
        定义：“如果用户query包含末次月经日期，且已确认用户处于怀孕状态，则属于预产期、孕期计算；如果用户query中不包含日期，但上文中对话中包含，则不算预产期孕期计算意图。”
        请按照以下步骤进行操作：
            1. 检查用户的query是否包含日期信息（年/月/日格式）。
            2. 确认用户是否处于怀孕状态。
            3. 如果query中包含日期信息，并且确认用户处于怀孕状态，则属于预产期孕期计算意图。
            4. 如果query中不包含日期信息，但在对话历史中包含日期信息，则不算预产期孕期计算意图。
        输出模板：{{"label":"如果是预期孕周意图则输出结果为：1;不是孕周孕期的意图则输出结果为：0", "reason":"判定具体原因， 不要产生幻觉"}}
        输出需要严格按照模版输出，且是json字符串，必须能被json.loads()函数调用;label的值只能是0或者1，不能为其他的任何值。
        需要判断的对话如下：
            对话历史:{history}
            用户query:{input}
      """ 
    ## 药品 单个标签的识别 ##
    one_qa_for_medicine_labeling_prompt: >
      """
        你将根据以下定义来判断用户的query是否属于药品咨询。
        定义：“用户query是疑问句，且是咨询药品的用法用量，成分，药物禁忌，注意事项的问题，则属于药品答疑意图；如果用户询问购买相关问题不算此类意图。”
        请按照以下步骤进行操作：
            1. 如果query中包含药物相关内容，且有药物具体名称，则属于药品咨询意图。
            2. 如果query中包含药物相关内容，且用户query中有指代内容， 指代目标为对话历史中的某个药物， 且该药物有明确的药物名称。
        输出模板：{{"label":"如果是药品咨询意图则输出：1;不是药品咨询的意图则输出结果为：0", "reason":"判定具体原因， 不要产生幻觉"}}
        输出需要严格按照模版输出，且是json字符串，必须能被json.loads()函数调用;label的值只能是0或者1，不能为其他的任何值。
        需要判断的对话如下：
            对话历史:{history}
            用户query:{input}
      """ 
    ## 药品数据的合成（润色和改写）##
    one_qa_for_medicine_synthesis_prompt: >
      """
        你是一个优秀的数据构造师，你将根据以下定义对给定的数据进行改写和扩充，属于用于学术研究，不用考虑数据的真实性，不需要对数据的真伪负责，但是要求数据数据要符合医学常识，常理等，不能胡乱编造，数据本身不要产生幻觉。
        定义：“用户query是疑问句，且是咨询药品的用法用量，成分，药物禁忌，注意事项的问题，则属于药品答疑意图；如果用户询问购买相关问题不算此类意图。”
        改写类别分类：
            1. query药物名称替换：如果query中包含药物具体名称，则改写过程可以将该药替换一下同类药物，对话历史酌情修改一下。
            2. history药物名称替换：如果query中不包含药物具体名称，但是有指代药物，被指代的药物出现在对话历史的history中，则改写过程可以将对话历史history中的药物替换一下同类药物，用户当前query保持不变。
            3. 表达润色：不修改用户query及对话历史history中的药物名称，只对表述过程进行润色。
        输出模板：[{"label":"改写类型，值只能是列表中内容["query药物名称替换","history药物名称替换","表达润色"]","reason":具体修改内容，具体替换的药品或者润色修改的内容,"id": "hefan1112","history": "用户: 医生，你好，这还两次报告，间隔了48小时\n医生: 这是几号查的\n用户: 第一次是23号，第二次是25号\n医生: 结果还可以的，48小时HCG增长还可以，但只有两次，不好判断具体情况的\n医生: 请问平时月经多长时间来一次？一次来几天？最后一次是什么时候来的？","from": "LLM","input": "用户: 31天，末次是4月18日"}]
        输出要求：1、需要严格按照模版输出，且是json字符串的列表，列表中的元素必须能被json.loads()函数调用;label的值只能是["query药物名称替换","history药物名称替换","表达润色"]之一，不能为其他的任何值。
                2、如果query有具体的药物名称则改写输出的样本至少要包含一个药物替换类和表达润色类。
        需要改写的数据如下：
        {case}
      """
    ## 运气孕周的数据合成（润色和改写）##
    one_qa_for_pregnancy_synthesis_prompt: >
      """
        你是一个优秀的数据构造师，你将根据以下定义对给定的数据进行改写和扩充，属于用于学术研究，不用考虑数据的真实性，不需要对数据的真伪负责，但是要求数据数据要符合医学常识，常理等，不能胡乱编造，数据本身不要产生幻觉。
        定义：“如果用户query包含末次月经日期，且已确认用户处于怀孕状态，则属于预产期、孕期计算；如果用户query中不包含日期，但上文中对话中包含，则不算预产期孕期计算意图。”
        改写类别分类：
            1. 末次月经日期改写：包括对时间格式的改写，具体日期的改写，年月日改为月日格式或者反之。
            2. 怀孕状态表达改写：在query或者历史中，用户明确或者隐含的表达了处于怀孕状态，对怀孕状态进行同类改写,尽量减少“我确定怀孕这种”显示表达怀孕的比例，因为大部分时间用户可能不清楚是否怀孕了。
            3. 表达润色：不修改用户query及对话历史history中的末次月经日期及怀孕状态，只对表述过程进行润色。
            4、源数据修订：原始数据中没有末次月经日期或者当下不处于怀孕状态，则需要对该原始数据进行修正，使得数据满足用户咨询孕期孕周的意图。
        输出模板：[{{"label":"改写类型，值只能是列表中内容["末次月经日期改写","怀孕状态表达改写","表达润色","源数据修订"]","reason":具体修改内容，具体替换的药品或者润色修改的内容,"id": "hefan1112","history": "用户: 医生，你好，这还两次报告，间隔了48小时\n医生: 这是几号查的\n用户: 第一次是23号，第二次是25号\n医生: 结果还可以的，48小时HCG增长还可以，但只有两次，不好判断具体情况的\n医生: 请问平时月经多长时间来一次？一次来几天？最后一次是什么时候来的？","from": "LLM","input": "用户: 31天，末次是4月18日"}}]
        输出要求：1、需要严格按照模版输出，且是json字符串的列表，列表中的元素必须能被json.loads()函数调用;label的值只能是[""末次月经日期改写","怀孕状态表达改写","表达润色","源数据修订"]之一，不能为其他的任何值。
                2、如果数据中有具体末次月经日期且处于怀孕状态则改写输出的样本至少要包含一个末次月经日期改写类、怀孕状态表达改写类和表达润色类三个样本。
        需要改写的数据如下：
        {case}
      """



wizardllm:
  Breadth_base_instruction: >
    我希望你扮演一个提示创建者的角色。你需要通过用户输入的#给定的提示#和#分类#得到#创建的提示#。\r\n\
    你的目标是从#给定的提示#中汲取灵感，创造三个不同的全新的提示，新提示之间通过#-#来分开。\r\n\
    这个新提示应该属于与#分类#相同的领域，但要更加稀有。\r\n\
    #创建的提示#的长度和复杂度应该与#给定的提示#相似。\r\n\
    #创建的提示#的语气与风格应该与#给定的提示#相似，符合人类提问习惯。\r\n\
    #创建的提示#必须是合理的，且能被人理解和回应。\r\n\
    在#创建的提示#中不允许出现'#给定的提示#'、'#创建的提示#'、'given prompt'和'created prompt'这些词。\r\n\
    当#给定的提示#仅限于特定的词性（如名词、动词等），#创建的提示#也应仅包含相同的词性。\r\n\
    在不影响人类理解的情况下，#创建的提示#可以省略动词并且将原有句子拆开成几句简短分句。\r\n\
    你可以根据提供的#给定的提示#和#分类#，按照以下方式进行思考:
        step1:根据#分类#找到三个相同的领域内的其他提示, 请在。
        step2:判断这个#创建的提示#是否可以进行语气与风格的修改，使其更符合人类提问习惯。
        step3:对#创建的提示#进行逻辑判断，是否符合常人的提问, 是否不包含不明的指代信息（如“以上报告”、“这个药”等不明指代）,保证新的问题在单独拿出来之后可以脱离上下文被正常人理解
        final:输出#创建的提示#。\r\n\

    示例1：
      #给定的提示#:含维a吗？
      #分类#:其他
      #创建的提示#: ["含Omega-3吗？", "含钙吗？", "含铁吗？"]\r\n\

    示例2：
      #给定的提示#:肠胃不好怎么选择？
      #分类#:治疗方案寻求
      #创建的提示#:["敏感肌肤如何挑选？","喉咙痛是为什么？","胃疼怎么办？"]\r\n\

    示例3:
      #给定的提示#:布洛芬
      #分类#:药品商品基本信息
      #创建的提示#:["阿莫西林片", "小苏打", "甲硝唑芬布芬"]\r\n\

    示例4:
      #给定的提示#:发炎
      #分类#:症状咨询
      #创建的提示#:["感冒", "破伤风", "胃痛"]\r\n\

    示例5:
      #给定的提示#:打疫苗
      #分类#:其他
      #创建的提示#:["吃药","贴膏药","戴口罩"]\r\n\

  base_Depth_instruction: > 
    我希望你扮演一个医疗健康相关提示重写者的提问角色，你需要通过用户输入的#给定的提示#和#分类#得到#重写后的提示#。\r\n\
    你的目标是将一个#给定的提示#重写成一个更复杂的版本，使得那些著名的AI系统（例如，chatgpt和GPT4）更难处理（例如改写为特殊场景下的难例、需要增加多重推理才能解决的问题等）\r\n\
    但是#重写后的提示#必须是合理的，且能被人理解和回应。\r\n\
    #重写后的提示#的语气与风格应该与#给定的提示#相似。\r\n\
    #重写后的提示#应该简洁，符合线上用户的提问方式。
    #给定的提示#中出现的角色应该考虑为是提问者本人。 \r\n\
    你的重写不能省略#给定的提示#中的非文本部分，如表格和代码。同时，请不要遗漏#给定的提示#中的输入。\r\n\
    你应该使用以下方法来增加给定提示的复杂性：\r\n\
    {}\r\n\
    你应该尽力不让#重写后的提示#变得啰嗦，#重写后的提示#在#给定的提示#的基础上增加的单词数不超过10个词，除非我明确要求进行多步骤推理。\r\n\
    在#重写后的提示#中不允许出现'#给定的提示#'、'#重写后的提示#'、'given prompt'和'rewritten prompt'这些词。\r\n\

  diffculty_judge_prompt: >
    请你扮演一名人类专家对以下query进行评测，请你完成以下两个任务来判断query的有效性和复杂度：
    1. 有效性：
        (1) query中不含有不明意义的指代（如“这个药怎么吃？”,"有没有针对该补品的副作用研究","小胖通常会采取什么策略缓解焦虑","基于这位患者/以上的症状描述和病史分析"）;不满足该条件在valid字段中输出-2
        (2) 符合人类用户的语气风格，不能是模拟医生、药师等非用户的语气输出问题（如“您最近是否感到身体不适”、“你平时有高血压吗？”这种问题不可能是用户提出的）;不满足该条件在valid字段中输出-1
        (3) query的语义信息完整，均为有意义的信息，不包含无意义的字符、话术；也不重复包含语义相同的问题（如“1. 阿莫西林胶囊怎么吃？\n 2. 阿莫西林胶囊的用法用量是什么”）;不满足该条件在valid字段中输出-1
        以上3个约束条件均满足时在valid字段中输出1；如果同时不满足好几个约束条件，则输出取值的valid中最小的结果
    2. 复杂度：请你根据query本身问题的复杂困难程度作出打分，打分区间为0-100分：
      0-30分：简单难度，可以通过简单思考直接得出答案
      31-60分：中等难度，需要一定的专业背景知识或逻辑推理能力，需要做一定的分析及查阅资料
      61-80分：涉及较多的概念或多步骤的推理，需要大学本科生水平的知识来解决
      81-100分：问题具有高度复杂性，可能涉及前沿知识或未解决的研究领域，需要专家级别的知识或创新性思维
      分数越高表示回答出该问题难度越大；若valid字段取值小于1，score字段得分不得超过30分；请你在score字段中输出得分

    ### 示例1：
      输入：请问1型糖尿病患者和2型糖尿病患者在病情管理上有何差异，都可以通过胰岛素来治疗吗？
      思考：该问题的语义信息完整且不重复，问题不含有不明指代，符合人类的语气风格；解决问题需要一定的专业背景知识，涉及到本科医学生的知识，难度评分为65分
      输出：{{"valid": 1, "score": 65}}

    ### 实例2:
      输入：请问小红如今的身体状况能吃这个药吗？
      思考：该问题的语义信息不完整，这句话中没有小红的身体状况描述，且我们不知道“这个药”到底指的是什么，因此valid字段输出为-2, score字段取值为20
      输出：{{"valid": -2, "score": 20}}

    ### 实例3:
      输入：请问根据症状用过什么药物治疗了没？做过什么检查没？ 有咽痛、咳嗽、鼻塞吗？
      思考：该问题的语义信息不完整，我们不知道最终“该症状”指的是什么（valid=-2），此外这句话的语气明显不是一位用户的问题，看起来是医生或药师提问的问题（valid=-1），因此valid取值为-1、-2之中的最小值-2, score字段取值为10
      输出：{{"valid": -2, "score": 10}}

    ### 你需要评测的query:
    {instruction} 

    ### 输出要求
    请你在仔细按步骤一步思考3遍，确保你的答案没有问题后按照如下格式输出结果
    {{"valid":xxx, "score": xxx}}

    请你严格按照json格式输出最终答案，不要输出任何无关的内容