import argparse
import time

parser = argparse.ArgumentParser(description='Chinese Text Classification')
parser.add_argument("--model", type=str, default="/mnt/afs2/zhy/cache/models/ArmoRM-Llama3-8B-v0.1")
parser.add_argument("--engine", type=str, default="vllm", choices=["vllm"])
parser.add_argument("--device", type=str, default="0")
parser.add_argument("--dtype", type=str, default="float16")
parser.add_argument("--n", type=int, default=5)
parser.add_argument("--total_prompts", type=int, default=100, help="样本数量")
parser.add_argument("--repeat", type=int, default=1)
parser.add_argument("--temperature", type=float, default=1.0)
parser.add_argument("--top_p", type=float, default=1.0)
parser.add_argument("--max_tokens", type=int, default=512)
parser.add_argument("--save_interval", type=int, default=10)
parser.add_argument("--seed", type=int, default=None)
parser.add_argument("--timestamp", type=int, default=int(time.time()))
parser.add_argument("--control_tasks", type=str, default=None)
parser.add_argument("--system_prompt", action="store_true")
parser.add_argument("--early_stopping", action="store_true")
parser.add_argument("--skip_special_tokens", action="store_true")
parser.add_argument("--sanitize", action="store_true")
parser.add_argument("--shuffle", action="store_true")
parser.add_argument("--logits_processor", action="store_true")
parser.add_argument("--gpu_memory_utilization", type=float, default=0.8)
parser.add_argument("--max_model_len", type=int, default=8192)
parser.add_argument("--swap_space", type=int, default=4)
parser.add_argument("--tensor_parallel_size", type=int, default=1)
parser.add_argument("--repetition_penalty", type=float, default=1.0)

model_args = parser.parse_args()
